[package]
name = "rust-git"
version = "0.1.0"
authors = ["Sho Miyamoto <laveritefigaro@gmail.com>"]

[dependencies]
sha-1 = "0.7.0"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }